

# writing Test Driven Development
# firmware, software, hardware, and the relevant network configuration
# Software Development Life Cycle When Performing Software Testing
# Feature Testing: Unit tests, end-2-end tests, automated tests

name: CI/CD-deployment to QA environment/stage

on:
    push:
        branches: ['']
    pull_request:
        branches: ['']   

# QA should be an elevation of development environment
jobs:
    DeployQA:
        name: deployment to QA
        uses: actions/checkout@v4
        with:
            development_path: './'
        needs: [development_path]
    runs-on: Ubuntu-latest
    environment:
        name: QA
        url: ${{}}   
    
        
    steps:
        - run: npm run build --if present
        - run: npm run test
