on:
    push:
      branches: [ "master" ]
      path: ["Dockerfile", ".github/workflows/docker-image.yml"]
    pull_request:
      branches: [ "master" ]
  
      runs-on: ubuntu-latest
  
      steps:
      - name: checkout code
      - name: checkout master
      - uses: actions/checkout@v3
  
      - name: build and tag image
      - uses: docker/build-push-action@v4
        run: |
         docker build . \
         --tag ${{DOCKER_USER_NAME}}/${{IMAGE_NAME}}:$IMAGE_VERSION
  
      -name: login to docker hub/container
      -uses: docker/login-action@v4
      with:
         username: ${{env.DOCKER_USER_NAME}}
         password: ${{env.DOCKER_PASSWORD}}
        run: |
         docker login -u ${{DOCKER_USER_NAME}} -p ${{DOCKER_PASSWORD}}
  
      -name: Test
       run:|
       echo --running test cases--
         docker tag testing:v1 ${{DOCKER_USER_NAME}}/testing:v1
       echo --tests completed-- 
  
      -name: build and push docker image
      -name: Publishing the image to Dockerhub/registry
      -uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile 
        push: true
        secrets: |
           token: ${{GIT_AUTH_TOKEN}}
        run: |
         docker push ${{DOCKER_USER_NAME}}/${{DOCKER_IMAGE}}:${{IMAGE_VERSION}}
  
  
    deploy:
      runs-on: ubuntu-latest