on:
    push:
      branches: [ "development" ]
      path: ["Dockerfile", ".github/workflows/docker-image.yml"]
    pull_request:
      branches: [ "development" ]


jobs:
    deploy_QA:
        name: Build && Deploy to QA testing
        environment:
            name: Development
            url: https://github.com/clintSanch/ScalableUI/settings/environments/1587075091/edit
  
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout code
      - name: checkout master
      - uses: actions/checkout@v3
  
      - name: build and tag image
      - uses: docker/build-push-action@v4
        run: |
        docker build . \
        --tag ${{secrets.DOCKER_USER_NAME}}/${{IMAGE_NAME}}
  
      - name: login to docker hub/container
      - uses: docker/login-action@v4
        with:
        username: ${{secrets.DOCKER_USER_NAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        run: |
         docker login -u ${{secrets.DOCKER_USER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}
  
      - name: Test
        run: |
        echo --running test cases--
        docker tag testing:v1 ${{secrets.DOCKER_USER_NAME}}/testing:v1
        echo --tests completed-- 
  
      - name: build and push docker image
      - name: Publishing the image to Dockerhub/registry
      - uses: docker/build-push-action@v5
        with:
        context: .
        file: ./Dockerfile 
        push: true
        secrets: |
           token: ${{secrets.GIT_AUTH_TOKEN}}
        run: |
         docker push ${{secrets.DOCKER_USER_NAME}}/${{secrets.DOCKER_IMAGE}}:${{IMAGE_VERSION}}
  
name: Deployment

on:
    push:
        branches: ["master"]
        
    deploy:
      runs-on: ubuntu-latest
      environment:
        name: Production
        url: https://somehost.com

      steps:
        name: deploy