name: CI/CD Nodejs scalable-ui to Vercel

on:
    push:
        branches: ["development"]
    pull_request:
        branches: ["development"]
        
jobs:
    build:
        runs-on: ubuntu-latest
        environment: Development
        url: https://github.com/clintSanch/ScalableUI/settings/environments/1587075091/edit
        
        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]


        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}

            - name: Install dependencies
              run: npm ci
            - name: build now  
              run: npm run build
    tests:
    -name: Run Tests of scalable-ui against Vercel
    runs-on: ubuntu-latest
      run: npm test

     
    deployment:
    - name: Deploy scalable-ui to Production server
      uses: amondnet/vercel-action@v20
      env:
        github-token: ${{secrets.GITHUB_TOKEN}}
        vercel-token: ${{secrets.VERCEL_TOKEN}}
        vercel-org-id: ${{secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{secrets.VERCEL_PROJECT_ID}}
        working-directory: dist/ScalableUI
            
...
