name: Deploy to Vercel

env:
    VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
        
jobs:
    build:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]

        steps:
            - uses: actions/checkout@v3
            
            - name: Install Vercel CLI
              run: npm install 